# Generated by Django 3.2.13 on 2023-04-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='hash_tag',
            field=models.CharField(default='#hashtag', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitter_account',
            name='hash_tag',
            field=models.CharField(default='#hashtag', max_length=1024),
            preserve_default=False,
        ),
    ]
