# Generated by Django 3.2.13 on 2023-04-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_accounts', '0003_auto_20230410_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='stars',
        ),
    ]
